defaults:
  - scope:
      path: ""
    values:
      permissions-policy: "interest-cohort=()"

  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "SAMEORIGIN"
  X-XSS-Protection: "1; mode=block"
  